-- FNOL Reports Table
-- Stores First Notice of Loss reports generated by the CRASH agent system

CREATE TABLE IF NOT EXISTS fnol_reports (
    id BIGSERIAL PRIMARY KEY,

    -- Claim identification
    claim_number VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL,

    -- Event details
    policy_id INTEGER NOT NULL,
    vehicle_id INTEGER,
    driver_id INTEGER,
    vin VARCHAR(20),
    event_time TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Location
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    street VARCHAR(255),

    -- Impact analysis
    severity VARCHAR(20) NOT NULL,
    impact_type VARCHAR(50),
    speed_at_impact DOUBLE PRECISION,
    g_force DOUBLE PRECISION,
    was_speeding BOOLEAN,
    airbag_deployed BOOLEAN,

    -- Environment
    weather_conditions VARCHAR(100),
    road_surface VARCHAR(50),
    daylight_status VARCHAR(20),

    -- Policy info
    policy_number VARCHAR(50),
    driver_name VARCHAR(255),
    driver_phone VARCHAR(50),
    driver_email VARCHAR(255),
    vehicle_make VARCHAR(100),
    vehicle_model VARCHAR(100),
    vehicle_year INTEGER,

    -- Communications
    sms_sent BOOLEAN DEFAULT FALSE,
    push_sent BOOLEAN DEFAULT FALSE,
    adjuster_notified BOOLEAN DEFAULT FALSE,
    assigned_adjuster VARCHAR(255),
    roadside_dispatched BOOLEAN DEFAULT FALSE,

    -- Full JSON report for complete data
    report_json JSONB NOT NULL,

    -- Metadata
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_fnol_claim_number ON fnol_reports(claim_number);
CREATE INDEX IF NOT EXISTS idx_fnol_policy_id ON fnol_reports(policy_id);
CREATE INDEX IF NOT EXISTS idx_fnol_severity ON fnol_reports(severity);
CREATE INDEX IF NOT EXISTS idx_fnol_status ON fnol_reports(status);
CREATE INDEX IF NOT EXISTS idx_fnol_event_time ON fnol_reports(event_time);
CREATE INDEX IF NOT EXISTS idx_fnol_generated_at ON fnol_reports(generated_at);
