package com.insurancemegacorp.crash.communications;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Test controller for manually testing email functionality.
 * DELETE THIS FILE BEFORE PRODUCTION!
 */
@RestController
@RequestMapping("/test")
public class TestController {

    private final CommunicationsService communicationsService;

    public TestController(CommunicationsService communicationsService) {
        this.communicationsService = communicationsService;
    }

    @GetMapping("/email")
    public CommunicationsService.EmailResult testEmail() {
        return communicationsService.sendFnolEmail(
            "TEST-CLM-001",
            "Test Driver",
            "POL-TEST-001",
            "SEVERE",
            "This is a TEST FNOL report to verify email delivery.\n\n" +
            "Accident Details:\n" +
            "- Location: 123 Test Street, Atlanta, GA\n" +
            "- Time: " + java.time.Instant.now() + "\n" +
            "- Severity: SEVERE\n" +
            "- Impact Type: FRONTAL\n" +
            "- Vehicle: 2021 Toyota Camry\n" +
            "- G-Force: 8.5\n\n" +
            "This email was generated by the /test/email endpoint."
        );
    }
}
